### ISSUE TITLE
Upgrade library

### ISSUE THREAD

**Issue by Gemorroj** [winlibs/cyrus-sasl#1]
I have issue with this library https://github.com/mongodb/mongo-php-driver/issues/763
Can you update the library to latest tag of `cyrus-sasl` (https://github.com/cyrusimap/cyrus-sasl/releases)?
Unfortunately, my knowledge is not enough to build this library.

**Comment by weltling** [comment]
Thanks for the report. I found an issue with the current vc15 libsasl builds, so repackaged it. However it doesn't seem to be the issue you actually experience in the ticket. Unlikely an upgrade will be helpful therefore.

Thanks.

**Comment by Gemorroj** [comment]
info: https://github.com/cyrusimap/cyrus-sasl/compare/816e529043de08f3f9dcc4097380de39478b0b16...cyrus-sasl-2.1.27-rc7
the difference between used revision and the `cyrus-sasl-2.1.27-rc7` tag
But I could be wrong about the revision. Can you specify where the source code came from?

**Comment by weltling** [comment]
The sources come always from the corresponding upstreams. In this case, as we had to support OpenSSL 1.1.0, a libsasl RC was taken. That is kinda unusual, but an alternative were to leave ext/ldap out in the core then. OpenSSL adoption is still slow :(

As mentioned in another ticket, since same issue is shown on libssh 2.1.25 on your side, an upgrade is unlikely to help. Especially an upgrade to some other RC state, where 2.1.25 was stable for years with the lower OpenSSL version. As long as it is unclear, what causes an issue on your side, no change should happen. It seems to make the best sense to debug through the failing routine therefore, whereby unluckily the reproducibility is only limited to your environment right now.

Thanks.
